name: E2E Screenshot Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test-e2e:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Build and run Dev Container task
        uses: devcontainers/ci@513af61f4de4f75d37e4438f184ba4358f0fc1ca # v0.3.1900000450
        with:
          runCmd: |
            npm ci
            npm run build
            npm run test:e2e:install
            npm run test:e2e -- --update-snapshots=none
